# Builds the solution, runs unit + integration tests with coverage,
# and performs static analysis on SonarQube Cloud.

name: BuildTestAndStaticAnalysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-static-analysis:
    name: Build, Test & Static Analysis
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones reduce the relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin Sonar scan
        run: >
          dotnet sonarscanner begin
          /k:"Taja992_HotelBooking"
          /o:"taja992"
          /d:sonar.token="$SONAR_TOKEN"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
          /d:sonar.cs.vstest.reportsPaths="**/*.trx"

      - name: Restore dependencies
        run: dotnet restore HotelBooking.sln

      - name: Build
        run: dotnet build HotelBooking.sln --no-restore --configuration Debug

      - name: Test with coverage
        run: >
          dotnet test HotelBooking.sln
          --no-build
          --configuration Debug
          --logger "trx"
          --results-directory ./TestResults
          --collect:"XPlat Code Coverage"
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
